name: Build and Release Desktop Installers

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Native Package with Maven
        run: |
          mvn clean package
          mvn dependency:copy-dependencies -DoutputDirectory=target/libs
          jpackage --type dmg --name DoNotPassGoBanker --input target/ --module-path target/libs/ --main-jar DoNotPassGoBanker-1.jar --main-class Launcher --dest target/
          jpackage --type exe --name DoNotPassGoBanker --input target/ --module-path target/libs/ --main-jar DoNotPassGoBanker-1.jar --main-class Launcher --dest target/
        shell: bash

      - name: Upload Installer to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/DoNotPassGoBanker.dmg
            target/DoNotPassGoBanker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}